### ISSUE TITLE
Disallow include_subdomains from eTLDs

### ISSUE THREAD

**Issue by chlily1** [w3c/reporting#159]
We currently allow include_subdomains policies from effective top-level domains, e.g. com could set an include_subdomains policy and get reports about any *.com domain. Should we allow this?

My intuition is no, since this seems overly broad and allows collection of reports about multiple "entities", and my understanding is that include_subdomains is meant as a convenience to allow registering a single policy for subdomains belonging to the same "entity".

**Comment by dcreager** [comment]
I could call this out better in the spec but an `include_subdomains` policy can only be used to get reports about DNS failures.  Step 8 of [§5.4](https://w3c.github.io/network-error-logging/#generate-a-network-error-report-0) drops the report on the floor if it's not a DNS error, and an `include_subdomains` policy was used to report it.  Even if the same physical server served the response for both the superdomain response that installed the policy, and the subdomain request that's being reported on.  Does that address some of the concern?

**Comment by chlily1** [comment]
Right, I wasn't super concerned about NEL because of the limitation to DNS errors for subdomains reports. But I think this could potentially be a problem for other report types.

**Comment by dcreager** [comment]
Oh whoops, my bad, streams crossed!  We're in the reporting repo, aren't we? :grimacing:

**Comment by igrigorik** [comment]
@chlily1 wait, I'm confused.. 

> The OPTIONAL include_subdomains member is a boolean that enables this endpoint group for all subdomains of the current origin’s host. If no member named "include_subdomains" is present in the object, or its value is not "true", the endpoint group will not be enabled for subdomains. [spec](https://w3c.github.io/reporting/#include-subdomains-member)

> We currently allow include_subdomains policies from effective top-level domains, e.g. com could set an include_subdomains policy and get reports about any *.com domain. Should we allow this?

The former does not imply latter. Right?

**Comment by chlily1** [comment]
The former implies the latter in that it doesn't specify an exception for eTLDs, so (I'd guess that) implicitly they're allowed to set include_subdomains endpoint groups just like any other domain can. Am I reading the spec wrong?

**Comment by igrigorik** [comment]
How would one set a policy for an eTLD? 

Including `include_subdomains` in your policy, in the HTTP response, would be associated with the response origin's host — right? I think I'm missing something obvious here. :)

**Comment by chlily1** [comment]
Setting a policy via HTTP response header for an eTLD would work just like setting a policy for any domain/origin, no? There's currently no server at https://com or https://co.uk but there's nothing in theory preventing it.

For example, Verisign (which I believe controls com) could serve an include_subdomains policy on https://com that would be able to collect reports from any *.com domain that didn't specify their own policy. My thought is that this should not be allowed because *.com spans multiple entities and include_subdomains should be scoped to domains controlled by the same entity.

For a more plausible example, consider https://github.io, which is on the [Public Suffix List](https://publicsuffix.org/list/public_suffix_list.dat) and hence an eTLD. https://github.io currently serves a redirect but it could also serve a Report-To response header with an include_subdomains policy.

**Comment by igrigorik** [comment]
Hmm, good points. 

The case for disallowing [TLDs](https://en.wikipedia.org/wiki/List_of_Internet_top-level_domains#Types) (generic, country, etc) seems pretty straightforward. Albeit, I'm not sure if that's a thing in practice today? Are we aware of any such operational cases on the web today?

The case for eTLD is murky to me. For example, it doesn't seem unreasonable for GitHub to set a policy on github.io. That said, in that particular case they could also advertise the same policy on all the subdomains — shrug. 

@mikewest @noncombatant would love to hear your thoughts and guidance on this one. I suspect you may have discussed this already in context of CSP, HSTS, etc.

**Comment by dcreager** [comment]
There's also a big difference between how CSP/NEL/etc interact with Reporting, vs Interventions/Crash Reports/etc, that's worth calling out.

The first have some kind of explicit config header field (`report_to`) that activates the Reporting integration, and chooses which Reporting endpoint group to deliver reports to.  For those specs, this behavior will only crop up if a site owner chooses to install a CSP header with a `report_to` value, _doesn't_ also provide a `Report-To` header that defines that endpoint group, _and_ the TLD owner happens to have been able to install its own `include_subdomains` `Report-To` header that _does_ define that endpoint group.

For Interventions/etc (i.e., the report types defined directly in Reporting), there's no way to specify which Reporting endpoint group to use; the user agent always uses the endpoint group named `default` if it exists.  That makes it much easier for a TLD's catch-all `include_subdomains` reporting policy to apply — it can happen in the absence of any action on the subdomain owner.

I'm wondering if a better (though more drastic) solution is to remove `include_subdomains` from Reporting completely?  _NEL_ would still have `include_subdomains`, for the reasons mentioned up-thread, but it would be NEL's responsibility to figure out which Reporting policy to use to report a DNS error via an `include_subdomains` policy.  Ditto for CSP or any other spec in this category that _actively chooses_ to support subdomain policies, and includes the necessary language to make sure they're safe and privacy-perserving.

And that would eliminate the hole for Intervention/Crash Reports/etc — since there wouldn't be any subdomain Reporting policies anymore, it wouldn't be possible to inadvertently deliver those kinds of reports to _any_ superdomain, not just the TLDs/eTLDs.

Thoughts?

**Comment by chlily1** [comment]
> The case for disallowing TLDs (generic, country, etc) seems pretty straightforward. ... The case for eTLD is murky to me. For example, it doesn't seem unreasonable for GitHub to set a policy on github.io.

Sure, but things like co.uk, co.jp etc. are not bare TLDs but should probably be treated as such. One option is to disallow include_subdomains for the public ICANN-acknowledged eTLDs (the first section of the PSL) but not the private ones in the second section. But IMO that's a little messy.

> Albeit, I'm not sure if that's a thing in practice today? Are we aware of any such operational cases on the web today?

Many browsers (e.g. [Chromium](https://cs.chromium.org/chromium/src/net/cookies/cookie_util.cc?l=160&rcl=7b4d8a0ca4f3dbba375692313db009dbfe98bdad)) do not allow cookies to be set with a domain attribute that is on the PSL. This is [mentioned](https://tools.ietf.org/html/draft-ietf-httpbis-rfc6265bis-03#section-4.1.2.3) in the spec but is not an explicit requirement.

> I'm wondering if a better (though more drastic) solution is to remove `include_subdomains` from Reporting completely?

FWIW, I wouldn't mind that. I think another possibility would be for different report types to specify whether they are allowed to be delivered to superdomains or not.

**Comment by chlily1** [comment]
I have this Chromium patch up which is ready to land if there are no objections: https://crrev.com/c/1638599

(It discards include_subdomains endpoint groups that any eTLD attempts to set. It also affects NEL policies in the same way, to be consistent.)

**Comment by igrigorik** [comment]
@dcreager I'm a little worried that punting this problem to be defined by each individual spec will just make matters worse: an opportunity for different and incompatible behaviors that will confuse developers, not to mention, it's not clear why some reports would not allow it at all.

@chlily1 in the context of this discussion, personally I'm leaning towards the solution you're proposing in  crrev.com/c/1638599. However, I would (a) prefer that we first hear from @mikewest and (b) wire up a spec update before we land the patch to make sure that we're all on the same page.

**Comment by sburnett** [comment]
I'm curious if there are any good uses for `include_subdomains` outside of NEL, though. As far as I know, the only reason NEL needs it is to report errors about subdomains that the browser could never otherwise have connected to previously; that's why we limit to DNS errors in that case.

I don't think it's worth it to allow `include_subdomains` purely for the sake of convenience (e.g., just so one doesn't need to configure a bunch of subdomains to send Reporting headers).

**Comment by igrigorik** [comment]
I'm not convinced that the utility is restricted to NEL and HSTS. For example, it would be nice to allow a site owner to register a (single) policy that enables them to observe crashes, security, and other errors for all subdomains. That said, fair points, it's worth considering the pros and cons... 

What would be a con to allowing crash reports to be available with include_subdomains?

**Comment by mikewest** [comment]
1.  Restricting `report-to` processing to non-TLDs seems reasonable to me. It fits the general model of not storing cookies for TLDs or eTLDs, and I don't think we lose anything of value by punting on it. If GitHub wants to exert control over `*.github.io` it has the means to do so directly, so it doesn't lose anything by dropping this functionality. `com`, on the other hand, cannot do so directly, and should not be allowed to do so.

2.  I'm totally fine with removing `include_subdomains` entirely. That would align reporting with the origin model, allowing origins to make assertions only about themselves. That seems pretty reasonable to me.

    There are some existing mechanisms (NEL, HSTS) that have chosen to go beyond that, but I suspect those would be harder to get through in a world where we're hoping to get away from "site" as the unit of separation, [aiming for more](https://chromium.googlesource.com/chromium/src/+/master/docs/security/side-channel-threat-model.md#multiple-origins-within-a-siteinstance) isolation between origins when possible.

**Comment by chlily1** [comment]
Removing `include_subdomains` sounds fine to me.
Given that it will take a while to implement the removal, and Chromium M77 branch is coming up in a few days, I'm going to go ahead and land https://crrev.com/c/1638599 in the meantime just as a stopgap.

**Comment by clelland** [comment]
#170 removes `include_subdomains` from the spec. With that done, I don't think that integrating with the Public Suffix List is necessary -- is that right?

**Comment by chlily1** [comment]
That's right, but I think it's important enough to at least fix the TLD issue in the next Chrome release, until the full removal can be implemented.
