### ISSUE TITLE
Consider credential-less reporting

### ISSUE THREAD

**Issue by johnwilander** [w3c/reporting#161]
The only reference to credentials/cookies I see is in the section on [Attempt to deliver reports to endpoint](https://w3c.github.io/reporting/#try-delivery), and it says `credentials "include"`. Browsers with cross-site tracking protections are likely to automatically strip out any cookies for third-party reports if the third-party domain is handled as a (potential) tracker. Are credentials really needed? If they are, would you rather have browsers with tracking protections block the whole load if they are going to block the cookies/credentials?

**Comment by dcreager** [comment]
Thanks for the report, John! I think you're absolutely right about this. CSP uses `same-origin` for legacy report uploads (i.e. that use `report-uri` instead of `report-to`). I could see us going with `same-origin` or `omit`, but I agree that `include` is not the right answer here.

@igrigorik @yoavweiss Any thoughts?

**Comment by igrigorik** [comment]
`omit` seems like a sensible default for reporting. Don't recall why we chose `include` initially.

**Comment by dcreager** [comment]
> Don't recall why we chose `include` initially.

Probably bad copy-pasta, tbh! :sweat_smile: 

@mikewest Any context on why CSP chose `same-origin` instead of `omit`?

**Comment by mikewest** [comment]
I don't remember what we discussed at the time, but looking at it again today:

It's useful for reporting endpoints to be able to tie reports to users, both for an understanding of a report's uniqueness ("Is this affecting one user a lot, or every user a little?") and context ("Ah, I see. After this user put 8,546,123 things in their cart, the script exploded!"). Since same-origin CSP endpoints can embed whatever information they want in the URL (e.g. `https://same.site/reporting/?userid=12&secret=data`), this seemed like a reasonable middle ground between protecting user privacy by blocking cross-origin cookie delivery, while giving same-origin endpoints that extra diagnostic ability. 

That said, if moving to `omit` makes it more likely that other vendors will adopt the mechanism, I'm willing to propose changes to CSP as well.

**Comment by yoavweiss** [comment]
@johnwilander - Would a move to `same-origin` be reasonable from your perspective?
