### ISSUE TITLE
Remove "nel" example from standard text

### ISSUE THREAD

**Issue by pes10k** [w3c/reporting#167]
The `8. Sample Reports` text includes a "nel" / Network Error Logging report example.

This is not one of the report types described in the standard.  It would be good to be able to consider the Reporting API in general, distinct from the privacy concerns related to Network Error Logging.

It would be best to remove this report, and / or replace it with a different, standardized report example.

**Comment by clelland** [comment]
Since the split of Reporting from [Network Reporting](https://w3c.github.io/reporting/network-reporting.html) and the various report types (https://github.com/WICG/crash-reporting, https://github.com/WICG/deprecation-reporting, https://github.com/WICG/intervention-reporting), there are actually no report types defined by this specification.

However, the overall report structure *is* defined here, so the examples may be useful. WDYT about just marking the whole section non-normative, and putting a note here that the reports are examples only, and the bodies are defined elsewhere?

The alternative I can see is to remove the section entirely.

**Comment by pes10k** [comment]
I suggest removing the section entirely, or replacing with manufactured foo / bar style examples.  I have significant concerns with NEL in particular (even more so than with the other categories of reports) so my preference would be to avoid having the Reporting API spect itself seem to be committing or suggesting anything about the other types of reports

**Comment by clelland** [comment]
That makes sense; I can replace them with obviously-bogus sample reports, just so that we can still demonstrate the structure of the report envelope.
