### ISSUE TITLE
Report calls to console-methods like "console.error"

### ISSUE THREAD

**Issue by nuxodin** [w3c/reporting#176]
Using the console-api to report issues to the server, one would be able to track this issues without changing a lot.

### custom function to inform the server:
- does not work with third party scripts calling console.error
- invent a new api although we already have a api
- more to code

### wrap console methods
- line and col showing the position of the call in the console are then the position of the wrapper-function
- more to code

Wrapping console methods is what i actualy do.

**Comment by clelland** [comment]
I mentioned in #119 just now, that the main objection I've heard to proposals such as this is that we want to make sure this doesn't turn into a de facto general out-of-band communication mechanism.

Since #189, the core Reporting API no longer defines any report types. The best path forward for this idea would be to start an explainer, and a new repository on WICG to float the idea. Integration with reporting should be pretty straightforward with examples such as https://wicg.github.io/crash-reporting/ and https://www.w3.org/TR/CSP3/#reporting.
