### ISSUE TITLE
Document vs ECMAScript global environment

### ISSUE THREAD

**Issue by bakulf** [w3c/reporting#205]
There is a discrete level of confusion in the spec about Reports in Workers. Let me summarize it:

1. ReportingObserver is exposed to workers. They are registered in the ECMAScript global environment:
https://w3c.github.io/reporting/#observers
> "Each ECMAScript global environment has a registered reporting observer list, which is an ordered set of reporting observers."

2. But the reports belong to the document:
https://w3c.github.io/reporting/#document-configuration
> "Each document has an reports list, which is a list of reports."

if a report is generated in a worker, where should we store it? It seems to me that the spec should do one of these options: a. remove the worker support, b. use globals instead of documents.

**Comment by clelland** [comment]
I just had a question from @yutakahirano about this -- it turns out that we want to enable reports from workers for COEP reporting, so I'd rather not go with (a)

The current state comes from the fact that reports aren't necessarily tied to scripts: any fetch could cause CSP reports; markup could trigger deprecation reports; crash reports could be generated at any time. I'm actually not sure under what conditions a document might not be associated with a global, but it seems better to try to work with the concept of "Document or WorkerGlobalScope" as the place to store the reports themselves, unless we can know for certain that documents without globals cannot or should not trigger reports.

(ReportingObservers, on the other hand, are explicitly an ECMAScript concept. A document (or worker) needs a scripting context in order to instantiate and use reporting observers, so that really needs to be associated with the ECMAScript environment.)

**Comment by annevk** [comment]
All documents have a relevant global object and the document that came with the reporting endpoint definitely does.

It might still make sense to store state on the document rather than the environment though, it's been a bit of a tossup between APIs which is picked.

**Comment by clelland** [comment]
I wasn't certain -- my understanding was that some documents can be created without any scripting context (XHR response documents, DOMParser output, maybe more?), and I wasn't sure if the global, if it did exist, would always outlive the document.

The notes at https://html.spec.whatwg.org/multipage/browsers.html#windows seem to be a bit more cautious , saying that there's always a Window, *if* there's a browsing context.

**Comment by clelland** [comment]
I just created a pull request from #206 for this; realized I'd pushed it to a branch last month, but never merged it.

**Comment by clelland** [comment]
And thanks, @bakulf, for bringing it up; I probably would have forgotten about it completely otherwise. Please take a look and see if it fixes the actual issue you raised.

**Comment by clelland** [comment]
This should be resolved now; all of the relevant objects are now on the WindowOrWorkerGlobalScope (option b from the original report)
