### ISSUE TITLE
Incorrect timestamp format in the example report

### ISSUE THREAD

**Issue by ivanr** [w3c/reporting#209]
Example 3 contains the following line:

```
"anticipatedRemoval": "1/1/2020"
```

The timestamp should be in ISO 8601 format.

**Comment by clelland** [comment]
I'm not sure what version of the spec you're looking at; the latest editor's draft (https://w3c.github.io/reporting/) doesn't include that example anymore. It's been moved to [Deprecation Reporting](https://wicg.github.io/deprecation-reporting/), but the date has been fixed there in any case.

(It appears that it was fixed as part of #134, back in 2018-11. The original bug was #132, which has since been closed.)

**Comment by ivanr** [comment]
I was looking at https://www.w3.org/TR/reporting/ which (I now know) appears to be the latest published version and not the latest version overall. Great that the problem had been fixed.

Looking at Deprecation Reporting, however, I think the spec is needlessly vague about what the format is exactly and thus leaves it to interpretation. IIRC, ISO 8601 allows many formats. Spelling it out that only a full timestamp is allowed would make more sense, and make it easier to process reports consistently.

**Comment by clelland** [comment]
For deprecation reports, I don't know if it makes sense to require a full timestamp -- while we might have a version in mind that completely removes a feature, the precision of the actual release date, at least for Chrome, is only known to within about a week, and even that is subject to change. "2020-05-05Z12:34:56" is expressing quite a bit more precision than anyone expects.

Please file an issue on the deprecation reporting repo, though, so we can capture all of this, and make any changes if needed.
