### ISSUE TITLE
Are report type extensible?

### ISSUE THREAD

**Issue by Marwansabbouh** [w3c/reporting#250]
Hello team,

The standard seems really useful, but I am wondering if there is a way to extend the report types? Also, is the standard only meant to catch browser errors, or can we piggyback on the proposed standard to capture any code execution ever even on the server?

**Comment by clelland** [comment]
The report types are extended through other specifications, such as [Content Security Policy](https://www.w3.org/TR/CSP3/#reporting), [Intervention Reporting](https://wicg.github.io/intervention-reporting/) or [COOP/COEP reporting](https://github.com/camillelamy/explainers/blob/main/coop_reporting.md)

The standard is intended to be used for browser features, to catch errors caused by web site code which is executed in the browser, rather than on the server. That said, I don't think there's anything stopping any other mechanism from generating similar POST HTTP requests and sending them to reporting endpoint servers. (I haven't given any thought as to whether that's a *good* idea yet, though)
