### ISSUE TITLE
Friendly TAG Review: relation to lifecycle events

### ISSUE THREAD

**Issue by travisleithead** [w3c/reporting#54]
In response to https://github.com/w3ctag/design-reviews/issues/195

* Wondering how this reporting might be related to the lifecycle events being proposed by Shubie Panicker (e.g., there is thinking about adding lifecycle events -- i.e., pause/resume -- which should integrate into this solutions.)

**Comment by RByers** [comment]
Hmm, in what way might they interact?  Do you mean defining the timing of reports relative to lifecycle stages?

@spanicker, @igrigorik any thoughts on this?

**Comment by spanicker** [comment]
I think this thread is around automatically reporting lifecycle state changes / analytics via reporting API? (Or something else?)
This is interesting, and I started an internal thread on this topic around an API that would provide a way for the app to declaratively indicate a URL and data blob that would be sent to the server on behalf of the app, when the app exits or is stopped by the system etc. and whether this could be integrated with Reporting API. There is interest in such an API in the context of unload deprecation.

However @igrigorik did not think this was appropriate use of Reporting API because:
"1. Reporting API registration is done via headers. No JS access or overrides. This is intentional to prevent third party scripts from overriding origin settings; e.g. blocking security reports, etc.
For the use case here, 3P analytics is a key use case, which is a big functional mismatch.
2. The delivery format for Reporting is POST with well-defined JSON schema.
Popular analytics vendors tend to prefer GET's and have own formats."
