### ISSUE TITLE
Specify some report types to be "unobservable"?

### ISSUE THREAD

**Issue by RByers** [w3c/reporting#57]
The rough idea of `ReportingObserver` is that it's a JS interface for observing the same reports as available to the HTTP Reporting API.

We've discussed with @juliatuttle and @mikewest that for now we'd likely implement CSP reports as HTTP only.  It's our network stack (in our browser process) that knows about CSP, and at a minimum it would be somewhat messy to pass these reports down into blink for delivery to JavaScript.  So conceptually we thought reports would only "flow up" from JS to HTTP, never down from HTTP to JS.

But @patrickkettner points out that it feels really odd to have some reports available to JS and others not.  Even if that's what chromium will implement for now, do we really want to spec if that way? Or should we instead design the API to support all types of reports via `ReportingObserver` and (for now) say chromium just hasn't implemented the feature for CSP reports via JS?  Discussed a little [here](https://github.com/WICG/reporting/pull/47#pullrequestreview-61402819)

@juliatuttle @igrigorik @mikewest

**Comment by igrigorik** [comment]
There are some types of reports that will never be able to "flow up" (e.g. network error logging for navigations), as such I think we have to spec this in a flexible way that permits reports to be HTTP only; we can't and shouldn't make it a 1:1 requirement.

**Comment by mikewest** [comment]
> It's our network stack (in our browser process) that knows about CSP, and at a minimum it would be somewhat messy to pass these reports down into blink for delivery to JavaScript.

CSP might be a bad example here. It's not implemented in the network stack, but in both the browser process (for navigational requests) and Blink (for all other types). For the latter, we generate `SecurityPolicyViolationEvent` directly, for the former, we pass CSP reports down from the browser down to Blink to trigger events (see https://cs.chromium.org/chromium/src/content/browser/frame_host/render_frame_host_impl.cc?rcl=00cc2c33f434b92739f547e49564e00e2def68dc&l=1076).

Messy or not, it's the contract we agreed to. :)

> There are some types of reports that will never be able to "flow up" (e.g. network error logging for navigations)

I do agree with this point, though: there are certainly report types that cannot generate events because there's no page to poke. That seems fine to acknowledge in the spec.

**Comment by dcreager** [comment]
Closing; the spec allows report types to declare that they are not visible to ReportingObservers.  (#110 also addresses the "no page to poke" part in terms of the URL that the reports describe.)
