### ISSUE TITLE
Buffer reports for handling "boot-time" with ReportingObserver?

### ISSUE THREAD

**Issue by RByers** [w3c/reporting#59]
Best practice for analytics libraries is to load them asynchronously, yet it's valuable for such libraries to be able to access the reports generated before the library was loaded.  To handle such cases @igrigorik [suggests](https://github.com/WICG/reporting/pull/47#discussion_r137701288) that we buffer reports up to some implementation-defined amount like PerformanceObserver [does](https://github.com/w3c/performance-timeline/issues/81).

The only problem I see with this is that I'd like to support a scenario where a library registers an observer only within the scope of it's own code.  Eg. maybe jQuery wants to call `observe()` on entry and `disconnect()` on exit in order to record JS-based deprecation/intervention reports triggered by jQuery code (while ignoring reports generated by other code).  In that case you definitely don't want your observer callback invoked for reports that occurred before `observe` was invoked.

So I suggest we add a (implementation-defined-size) buffer of reports, and a `ReportingObserverOption` like `futureOnly` (default false).  When false, we'd immediately queue any reports in the buffer to the observer.

@mikewest @patrickkettner @paulmeyer90 thoughts?

**Comment by patrickkettner** [comment]
I think its a great idea.

It would be good to figure out what the lifetime of the buffer is expected to be. For example

User loads a page
after N amount of time Reports begin to queue that jQuery requested.
Before they are dispatched observer, the page is closed. 
time passes, seasons change
User loads the same page


Does jQuery's observer get the previously queued content that had not been dispatched? Or should a queue be cleared at some arbitrary point (onbeforeunload gets weird if we support ServiceWorker, so I am not sure there is an obvious place)

**Comment by RByers** [comment]
Ignoring the service worker case for a minute (lots of design questions to figure out there - #50), I think we can just say the buffer lives for the life of the page - exactly like PerformanceObserver, right?

**Comment by patrickkettner** [comment]
So in this case those events would be dropped? Barring something like
takeReports() being used?

As of now I can't think of anything where that would be a major loss of
data, so I'm fine with that. It definitely complicates the SW case if we
want the same interface in both places, but no reason to block on that for
now


On Nov 11, 2017 8:39 AM, "Rick Byers" <notifications@github.com> wrote:

Ignoring the service worker case for a minute (lots of design questions to
figure out there - #50 <https://github.com/WICG/reporting/issues/50>), I
think we can just say the buffer lives for the life of the page - exactly
like PerformanceObserver, right?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/WICG/reporting/issues/59#issuecomment-343677159>, or mute
the thread

**Comment by RByers** [comment]
> So in this case those events would be dropped? Barring something like
takeReports() being used?

Right, if you never install an observer at all during the document lifetime, then the events will be lost (but still delivered to any http endpoints of course).  Depending on #58, you may or may not need to remember to invoke takeRecords on unload to maximize the chance of getting reports, but I think that's orthogonal to this issue.

**Comment by patrickkettner** [comment]
Sounds good to me

**Comment by RByers** [comment]
Done: http://w3c.github.io/reporting/#report-buffer
