### ISSUE TITLE
Endpoint groups and load balancing / failover

### ISSUE THREAD

**Issue by mnot** [w3c/reporting#93]
With the [endpoints member](http://wicg.github.io/reporting/#endpoints-member), Reporting defines a mechanism for load balancing and failover requests amongst multiple services.

These tasks are generic to all fetches, not just for reporting, and there are several well-established industry practices for addressing these needs.

If a client-side mechanism for doing this is going to be defined, it would be better addressed with a mechanism that works for all fetches; not only would it be more broadly useful, it would also enjoy better review than something defined deep in a very narrow specification.

This might be through a fetch() extension, or through adoption of SRV, for example.

Defining these capabilities in Reporting only adds to complexity -- both in implementation and in the task of adoption. It's a form of premature optimisation, and inappropriate specialisation.

Please consider removing this capability from the Reporting specification; the requirements can be addressed by existing mechanisms in the short term, and more generic ones in the medium-to-long term.

If there are reasons as to why this is not acceptable, it's important to document why that's the case (e.g, in the Introduction).

**Comment by mnot** [comment]
There's been a long history of people asking for SRV support from browsers; it's really up to them. There's certainly demand for it.

I was thinking of a flag, yes. Otherwise, you'd have to somehow feed the appropriate information into Fetch -- certainly possible if there's some objection to supporting SRV, but not nearly as easy.

WRT batching - yes, I think you'd have to reformulate to create multiple requests, and Fetch would need to be able to balance on a per-request basis. It might be good to be able to give it hints about what kind of balancing between weights is desired (per-connection, per-request, etc.); this would need to be thought through and defined. 

@annevk @mcmanus any thoughts?

**Comment by annevk** [comment]
If SRV is https://en.wikipedia.org/wiki/SRV_record a problem seems to be that it comes from DNS, which isn't trustworthy. And I think another problem with DNS is that middleware and certain OS's make it hard to use new types of records (iirc that's one of the things that makes DNSSEC not work).

I tend to agree with @mnot that adding a feature such as this in a v0/v1 is quite a bit beyond MVP.

**Comment by dcreager** [comment]
> adding a feature such as this in a v0/v1 is quite a bit beyond MVP

I agree with that too.  How about I mark this as a possible v2 feature, and add some text to the intro explaining that if a future version of Fetch provides the necessary load-balancing for us (whether based on SRV or not), we'd update Reporting to take advantage of it?

**Comment by annevk** [comment]
Sure. (I don't directly see how we'd go about that in Fetch, but happy to explore.)

**Comment by dcreager** [comment]
Anne pointed out in #94 that we weren't on the same page about what exactly would be the "v2 feature".

I was suggesting that we keep the current failover and load balancing logic here in Reporting, and that moving that text into Fetch is what we'd consider for v2.  Especially for NEL, we can't rely on purely server-side techniques, since the reliability of that server-side infrastructure is exactly what we're trying to monitor.  We need something client-side, and already have the current text spec'ed and implemented in Chrome.

I wrote the text in #94 to address some of @mnot's concerns — particularly that we're trying to reuse existing best practice for client-side load balancing (mimicking what's in SRV) instead of inventing something new, and acknowledging that in the future we'd prefer to have the load balancing be a general feature of Fetch and not something custom to Reporting.

@mnot, is that what you were thinking — and if not, is this an acceptable compromise?

**Comment by dcreager** [comment]
NEL is the spec that really needs client-side failover in the v0 MVP.  The failover logic was originally defined in NEL itself, before we extracted it out into Reporting (wicg/network-error-logging#67).  The current weight/priority logic is already [implemented](https://chromium-review.googlesource.com/c/chromium/src/+/797445) (though not shipped) in Chrome.

We can't rely on server-side failover (behind a single upload URL) for NEL because if a user loses network connectivity to that URL, then we lose all visibility into network errors for that user.  That's especially bad for NEL since those kinds of outages are precisely when its signal is most needed.

Instead we need to have the list of failover paths available in the client **_before_** a network outage occurs.  This is based on our experience with NEL's predecessor in Chrome, Domain Reliability.  We use a [list of upload URLs](https://cs.chromium.org/chromium/src/components/domain_reliability/google_configs.cc?l=530&rcl=f0084788eb8c5b667428391847e67259404f27e1) to try different paths to get the reports to our collectors — e.g., choosing a different front-end location, resolving the domain names via a different DNS provider, etc.  NEL needs a similar capability in Reporting.

**Comment by mnot** [comment]
Just a thought -- this almost seems like a job for Origin Policy. @mikewest?

**Comment by mnot** [comment]
https://github.com/whatwg/url/issues/398 seems slightly related, FWIW. At least, a sign of demand for something similar.

**Comment by mikewest** [comment]
> Just a thought -- this almost seems like a job for Origin Policy.

That's my eventual goal, yes. But Chrome's prototype is dragging, and it doesn't look like any other vendor is paying attention. Blocking on that might take a while.

**Comment by martinthomson** [comment]
We're paying attention.  It's likely that we'll want to get to that before we start doing the network-y bits of Feature Policy.

**Comment by mikewest** [comment]
Oh, great! Who on y'all's side is looking into that? I'd love to collaborate on the spec, as it's way out of date and needs work. :)

**Comment by caub** [comment]
python 'supports' it https://repl.it/@caub/python-url-1

```python
from urllib.parse import parse_qs, urlparse

u = urlparse('https://foo@server1.foo.ai:7998,server2.foo.ai:7998,server3.foo.ai:7998/data?authMechanism=X509&replicaSet=rs0&ssl=true&sslValidate=true')

print(u.hostname) # server1.foo.ai
print(u.netloc) # foo@server1.foo.ai:7998,server2.foo.ai:7998,server3.foo.ai:7998
```

**Comment by dcreager** [comment]
Even with Mozilla collaborating on Origin Policy, it won't be squared away in the near future, right?  Given all of the above, are we okay with keeping the current weight/priority logic in Reporting for v1?  We can use our experience with that to inform what it looks like in Origin Policy / Fetch proper / wherever else it ends up.

**Comment by dcreager** [comment]
Hearing no objections, I'm going to merge #94 and keep the current load balancing / failover text in Reporting.  I've opened whatwg/fetch#775 to track the discussion about whether we can move this into Fetch / Origin Policy.
